import { Article } from "@/components/article-preview/article-preview.component";

export const PRESS_ARTICLES_EN: Article[] = [
  {
    title: `"Prandi Foundation 2025 Solidarity Aid Award to a Project to Reduce Malnutrition and Improve Child Health in Benin"`,
    imageUrl: "/logos/ogimage.jpg",
    description: "",
    date: "November 6, 2025",
    link: "https://www.corresponsables.com/actualidad/premio-ayuda-solidaria-de-la-fundacion-prandi-2025-a-un-proyecto-para-reducir-la-malnutricion-y-mejorar-la-salud-infantil-en-benin/",
  },
  {
    title: `"Pozuelo presents the Iniciativa Awards recognising effort and entrepreneurship"`,
    imageUrl: "/logos/diario-de-pozuelo-logo.png",
    description: "",
    date: "November 29, 2022",
    link: "https://www.diariodepozuelo.es/111371-pozuelo-entrega-los-premios-iniciativa-para-reconocer-el-esfuerzo-y-el-espiritu-emprendedor",
  },
  {
    title: `"Brave women of Benin who dance against gender-based violence"`,
    imageUrl: "/logos/el-pais-logo.jpg",
    description: "",
    date: "December 24, 2021",
    link: "https://elpais.com/planeta-futuro/en-primera-linea/2021-12-24/mujeres-valientes-de-benin-que-bailan-contra-la-violencia-machista.html",
  },
  {
    title: `"The transformation of shea butter, an economy with a woman's face"`,
    imageUrl: "/logos/diario-responsable-logo.png",
    description: "",
    date: "December 26, 2019",
    link: "https://diarioresponsable.com/noticias/28625-manteca-de-karite-una-economia-de-mujeres",
  },
  {
    title: `"UVA students dig into their final degree projects on improving maternal and child health in Benin"`,
    imageUrl: "/logos/la-vanguardia-logo.jpg",
    description: "",
    date: "September 22, 2019",
    link: "https://www.lavanguardia.com/vida/20160922/41496753488/estudiantes-de-la-uva-ahondan-en-sus-trabajos-fin-de-grado-en-la-mejora-de-la-salud-materno-infantil-en-benin.html",
  },
  {
    title: `"AUARA launches #NombresConHistoria, with testimonies on how the lives of those who gain access to clean water have changed"`,
    imageUrl: "/logos/la-vanguardia-logo.jpg",
    description: "",
    date: "December 6, 2018",
    link: "https://www.lavanguardia.com/vida/20181206/453396825596/auara-lanza-nombresconhistoria-con-testimonios-sobre-como-ha-cambiado-la-vida-de-quienes-acceden-al-agua-potable.html",
  },
  {
    title: `"The Rodolfo Benito Samaniego Foundation honours Souad Benkaddour and OAN International"`,
    imageUrl: "/logos/la-luna-de-alcala-logo.png",
    description: "",
    date: "March 7, 2018",
    link: "https://lalunadealcala.com/la-fundacion-rodolfo-benito-samaniego-premia-a-souad-benkaddour-y-oan-international/",
  },
  {
    title: `"University solidarity with a double reward"`,
    imageUrl: "/logos/el-mundo-diario-valladolid-logo.jpg",
    description: "",
    date: "January 11, 2018",
    link: "https://diariodevalladolid.elmundo.es/articulo/valladolid/solidaridad-universtaria-doble-recompensa/20180111122630241952.html",
  },
  {
    title: `"The sustainable development of Africa, in the hands of Spanish university students"`,
    imageUrl: "/logos/el-mundo-logo.jpg",
    description: "",
    date: "October 15, 2017",
    link: "https://www.elmundo.es/sociedad/2017/10/15/59e242deca4741af078b4648.html",
  },
  {
    title: `"A solar autoclave for a hospital in Benin, Veolia Foundation Student Solidarity Award"`,
    imageUrl: "/logos/enery-news-logo.jpg",
    description: "",
    date: "July 27, 2017",
    link: "https://www.energynews.es/un-autoclave-solar-premio-solidaridad-estudiantil-de-la-fundacion-veolia/",
  },
  {
    title: `"A Spanish project wins the audience award at the Veolia Foundation "Student Solidarity Awards""`,
    imageUrl: "/logos/ogimage.jpg",
    description: "",
    date: "July 11, 2017",
    link: "https://www.retema.es/noticia/un-proyecto-espanol-se-lleva-el-premio-del-publico-en-los-premios-solidaridad-estudia-aJgIG",
  },
  {
    title: `"A low-cost solar oven devised at UVA, awarded and bound for Africa"`,
    imageUrl: "/logos/el-norte-de-castilla-logo.jpg",
    description: "",
    date: "June 21, 2017",
    link: "https://www.elnortedecastilla.es/valladolid/horno-solar-bajo-20170621172658-nt.html",
  },
  {
    title: `"Can missionaries and NGOs work together?"`,
    imageUrl: "/logos/el-pais-logo.jpg",
    description: "",
    date: "April 28, 2017",
    link: "https://elpais.com/elpais/2017/04/07/africa_no_es_un_pais/1491552240_287798.html",
  },
  {
    title: `"OAN International's scientific cooperation project reaches schoolchildren"`,
    imageUrl: "/logos/agencia-iberoamericana-logo.jpg",
    description: "",
    date: "November 8, 2016",
    link: "https://www.dicyt.com/viewNews.php?newsId=36461",
  },
  {
    title: `"Healthcare volunteering, an experience towards humanisation"`,
    imageUrl: "/logos/gaceta-medica-logo.jpg",
    description: "",
    date: "October 21, 2016",
    link: "https://gacetamedica.com/politica/el-voluntariado-sanitario-una-experiencia-hacia-la-humanizacion-MA561925/",
  },
  {
    title: `"Final Degree Projects to improve maternal and child health in Benin"`,
    imageUrl: "/logos/europa-press-logo.png",
    description: "",
    date: "September 22, 2016",
    link: "https://www.europapress.es/castilla-y-leon/noticia-estudiantes-uva-ahondan-trabajos-fin-grado-mejora-salud-materno-infantil-benin-20160922134719.html",
  },
  {
    title: `"UVA students dig into their Final Degree Projects on improving maternal and child health in Benin"`,
    imageUrl: "/logos/20-minutos-logo.png",
    description: "",
    date: "September 22, 2016",
    link: "https://www.20minutos.es/noticia/2844448/0/estudiantes-uva-ahondan-sus-trabajos-fin-grado-mejora-salud-materno-infantil-benin/",
  },
  {
    title: `"Something more than studying"`,
    imageUrl: "/logos/abc-logo.jpg",
    description: "",
    date: "February 18, 2016",
    link: "https://www.oaninternational.org/uploads/3/7/7/0/37702469/untitledj.pdf",
  },
  {
    title: `"OAN International. A small NGO of Spanish university students"`,
    imageUrl: "/logos/la-vanguardia-logo.jpg",
    description: "",
    date: "August 25, 2015",
    link: "https://www.oaninternational.org/uploads/3/7/7/0/37702469/captura_de_pantalla_2016-02-23_a_las_8.48.04.png",
  },
];
