import { Article } from "@/components/article-preview/article-preview.component";

export const PRESS_ARTICLES_FR: Article[] = [
  {
    title: `"Prix Aide Solidaire de la Fondation Prandi 2025 à un projet pour réduire la malnutrition et améliorer la santé infantile au Bénin"`,
    imageUrl: "/logos/ogimage.jpg",
    description: "",
    date: "6 novembre 2025",
    link: "https://www.corresponsables.com/actualidad/premio-ayuda-solidaria-de-la-fundacion-prandi-2025-a-un-proyecto-para-reducir-la-malnutricion-y-mejorar-la-salud-infantil-en-benin/",
  },
  {
    title: `"Pozuelo remet les Prix Iniciativa qui récompensent l'effort et l'entrepreneuriat"`,
    imageUrl: "/logos/diario-de-pozuelo-logo.png",
    description: "",
    date: "29 novembre 2022",
    link: "https://www.diariodepozuelo.es/111371-pozuelo-entrega-los-premios-iniciativa-para-reconocer-el-esfuerzo-y-el-espiritu-emprendedor",
  },
  {
    title: `"Des femmes courageuses du Bénin qui dansent contre les violences sexistes"`,
    imageUrl: "/logos/el-pais-logo.jpg",
    description: "",
    date: "24 décembre 2021",
    link: "https://elpais.com/planeta-futuro/en-primera-linea/2021-12-24/mujeres-valientes-de-benin-que-bailan-contra-la-violencia-machista.html",
  },
  {
    title: `"La transformation du beurre de karité, une économie au visage de femme"`,
    imageUrl: "/logos/diario-responsable-logo.png",
    description: "",
    date: "26 décembre 2019",
    link: "https://diarioresponsable.com/noticias/28625-manteca-de-karite-una-economia-de-mujeres",
  },
  {
    title: `"Des étudiants de l'UVA approfondissent leurs travaux de fin d'études sur l'amélioration de la santé materno-infantile au Bénin"`,
    imageUrl: "/logos/la-vanguardia-logo.jpg",
    description: "",
    date: "22 septembre 2019",
    link: "https://www.lavanguardia.com/vida/20160922/41496753488/estudiantes-de-la-uva-ahondan-en-sus-trabajos-fin-de-grado-en-la-mejora-de-la-salud-materno-infantil-en-benin.html",
  },
  {
    title: `"AUARA lance #NombresConHistoria, avec des témoignages sur la façon dont la vie de ceux qui accèdent à l'eau potable a changé"`,
    imageUrl: "/logos/la-vanguardia-logo.jpg",
    description: "",
    date: "6 décembre 2018",
    link: "https://www.lavanguardia.com/vida/20181206/453396825596/auara-lanza-nombresconhistoria-con-testimonios-sobre-como-ha-cambiado-la-vida-de-quienes-acceden-al-agua-potable.html",
  },
  {
    title: `"La Fondation Rodolfo Benito Samaniego récompense Souad Benkaddour et OAN International"`,
    imageUrl: "/logos/la-luna-de-alcala-logo.png",
    description: "",
    date: "7 mars 2018",
    link: "https://lalunadealcala.com/la-fundacion-rodolfo-benito-samaniego-premia-a-souad-benkaddour-y-oan-international/",
  },
  {
    title: `"Solidarité universitaire à double récompense"`,
    imageUrl: "/logos/el-mundo-diario-valladolid-logo.jpg",
    description: "",
    date: "11 janvier 2018",
    link: "https://diariodevalladolid.elmundo.es/articulo/valladolid/solidaridad-universtaria-doble-recompensa/20180111122630241952.html",
  },
  {
    title: `"Le développement durable de l'Afrique, entre les mains d'étudiants espagnols"`,
    imageUrl: "/logos/el-mundo-logo.jpg",
    description: "",
    date: "15 octobre 2017",
    link: "https://www.elmundo.es/sociedad/2017/10/15/59e242deca4741af078b4648.html",
  },
  {
    title: `"Un autoclave solaire pour un hôpital au Bénin, Prix Solidarité Étudiante de la Fondation Veolia"`,
    imageUrl: "/logos/enery-news-logo.jpg",
    description: "",
    date: "27 juillet 2017",
    link: "https://www.energynews.es/un-autoclave-solar-premio-solidaridad-estudiantil-de-la-fundacion-veolia/",
  },
  {
    title: `"Un projet espagnol remporte le prix du public aux « Prix Solidarité Étudiante » de la Fondation Veolia"`,
    imageUrl: "/logos/ogimage.jpg",
    description: "",
    date: "11 juillet 2017",
    link: "https://www.retema.es/noticia/un-proyecto-espanol-se-lleva-el-premio-del-publico-en-los-premios-solidaridad-estudia-aJgIG",
  },
  {
    title: `"Un four solaire à bas coût conçu à l'UVA, primé et en route vers l'Afrique"`,
    imageUrl: "/logos/el-norte-de-castilla-logo.jpg",
    description: "",
    date: "21 juin 2017",
    link: "https://www.elnortedecastilla.es/valladolid/horno-solar-bajo-20170621172658-nt.html",
  },
  {
    title: `"Missionnaires et ONG peuvent-ils travailler ensemble ?"`,
    imageUrl: "/logos/el-pais-logo.jpg",
    description: "",
    date: "28 avril 2017",
    link: "https://elpais.com/elpais/2017/04/07/africa_no_es_un_pais/1491552240_287798.html",
  },
  {
    title: `"Le projet scientifique de coopération d'OAN International s'adresse aux écoliers"`,
    imageUrl: "/logos/agencia-iberoamericana-logo.jpg",
    description: "",
    date: "8 novembre 2016",
    link: "https://www.dicyt.com/viewNews.php?newsId=36461",
  },
  {
    title: `"Le bénévolat sanitaire, une expérience vers l'humanisation"`,
    imageUrl: "/logos/gaceta-medica-logo.jpg",
    description: "",
    date: "21 octobre 2016",
    link: "https://gacetamedica.com/politica/el-voluntariado-sanitario-una-experiencia-hacia-la-humanizacion-MA561925/",
  },
  {
    title: `"Des travaux de fin d'études pour améliorer la santé materno-infantile au Bénin"`,
    imageUrl: "/logos/europa-press-logo.png",
    description: "",
    date: "22 septembre 2016",
    link: "https://www.europapress.es/castilla-y-leon/noticia-estudiantes-uva-ahondan-trabajos-fin-grado-mejora-salud-materno-infantil-benin-20160922134719.html",
  },
  {
    title: `"Des étudiants de l'UVA approfondissent leurs travaux de fin d'études sur l'amélioration de la santé materno-infantile au Bénin"`,
    imageUrl: "/logos/20-minutos-logo.png",
    description: "",
    date: "22 septembre 2016",
    link: "https://www.20minutos.es/noticia/2844448/0/estudiantes-uva-ahondan-sus-trabajos-fin-grado-mejora-salud-materno-infantil-benin/",
  },
  {
    title: `"Bien plus qu'étudier"`,
    imageUrl: "/logos/abc-logo.jpg",
    description: "",
    date: "18 février 2016",
    link: "https://www.oaninternational.org/uploads/3/7/7/0/37702469/untitledj.pdf",
  },
  {
    title: `"OAN International. Une petite ONG d'étudiants espagnols"`,
    imageUrl: "/logos/la-vanguardia-logo.jpg",
    description: "",
    date: "25 août 2015",
    link: "https://www.oaninternational.org/uploads/3/7/7/0/37702469/captura_de_pantalla_2016-02-23_a_las_8.48.04.png",
  },
];
